### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by ty666** [bilibili/discovery#64]
discovery 运行一段时间，发生了panic。 使用的是当前 [master](https://github.com/bilibili/discovery/tree/87e53c31856920901b940732bf0c4e0d5713e1e7) 分支的代码。

错误日志如下：
```
fatal error: concurrent map iteration and map write

goroutine 184 [running]:
runtime.throw(0xb15481, 0x26)
        /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc00051a940 sp=0xc00051a910 pc=0x439152
runtime.mapiternext(0xc000892ae0)
        /usr/local/go/src/runtime/map.go:853 +0x554 fp=0xc00051a9c0 sp=0xc00051a940 pc=0x412874
reflect.mapiternext(0xc000892ae0)
        /usr/local/go/src/runtime/map.go:1337 +0x2b fp=0xc00051a9d8 sp=0xc00051a9c0 pc=0x46afab
reflect.Value.MapKeys(0xa58200, 0xc0002125f8, 0x195, 0x0, 0xc000843560, 0x18)
        /usr/local/go/src/reflect/value.go:1226 +0x10c fp=0xc00051aa68 sp=0xc00051a9d8 pc=0x4a036c
encoding/json.mapEncoder.encode(0xb2b2d0, 0xc000990980, 0xa58200, 0xc0002125f8, 0x195, 0x100)
        /usr/local/go/src/encoding/json/encode.go:785 +0xff fp=0xc00051abe0 sp=0xc00051aa68 pc=0x549fbf
encoding/json.mapEncoder.encode-fm(0xc000990980, 0xa58200, 0xc0002125f8, 0x195, 0x100)
        /usr/local/go/src/encoding/json/encode.go:777 +0x65 fp=0xc00051ac20 sp=0xc00051abe0 pc=0x555ce5
encoding/json.structEncoder.encode(0xc0004d8000, 0xe, 0x10, 0xc000570a20, 0xc000990980, 0xadfb00, 0xc000212580, 0x199, 0xa50100)
        /usr/local/go/src/encoding/json/encode.go:759 +0x2ab fp=0xc00051acb8 sp=0xc00051ac20 pc=0x549c6b
encoding/json.structEncoder.encode-fm(0xc000990980, 0xadfb00, 0xc000212580, 0x199, 0xc000210100)
        /usr/local/go/src/encoding/json/encode.go:730 +0x7f fp=0xc00051ad10 sp=0xc00051acb8 pc=0x555c5f
encoding/json.ptrEncoder.encode(0xc000570a80, 0xc000990980, 0xa4d2c0, 0xc000212580, 0x16, 0xa40100)
        /usr/local/go/src/encoding/json/encode.go:915 +0x125 fp=0xc00051add0 sp=0xc00051ad10 pc=0x54b1e5
encoding/json.ptrEncoder.encode-fm(0xc000990980, 0xa4d2c0, 0xc000212580, 0x16, 0xc000210100)
        /usr/local/go/src/encoding/json/encode.go:900 +0x65 fp=0xc00051ae10 sp=0xc00051add0 pc=0x555e65
encoding/json.(*encodeState).reflectValue(0xc000990980, 0xa4d2c0, 0xc000212580, 0x16, 0xc000210100)
        /usr/local/go/src/encoding/json/encode.go:358 +0x82 fp=0xc00051ae48 sp=0xc00051ae10 pc=0x547362
encoding/json.interfaceEncoder(0xc000990980, 0xa4a1a0, 0xc0006411f0, 0x94, 0x100)
        /usr/local/go/src/encoding/json/encode.go:714 +0xac fp=0xc00051ae90 sp=0xc00051ae48 pc=0x5497cc
encoding/json.structEncoder.encode(0xc00066a480, 0x4, 0x4, 0xc0006417d0, 0xc000990980, 0xab8be0, 0xc0006411d0, 0x99, 0xab0100)
        /usr/local/go/src/encoding/json/encode.go:759 +0x2ab fp=0xc00051af28 sp=0xc00051ae90 pc=0x549c6b
encoding/json.structEncoder.encode-fm(0xc000990980, 0xab8be0, 0xc0006411d0, 0x99, 0xf20100)
        /usr/local/go/src/encoding/json/encode.go:730 +0x7f fp=0xc00051af80 sp=0xc00051af28 pc=0x555c5f
encoding/json.(*encodeState).reflectValue(0xc000990980, 0xab8be0, 0xc0006411d0, 0x99, 0xc000510100)
        /usr/local/go/src/encoding/json/encode.go:358 +0x82 fp=0xc00051afb8 sp=0xc00051af80 pc=0x547362
encoding/json.(*encodeState).marshal(0xc000990980, 0xab8be0, 0xc0006411d0, 0x100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:330 +0xf4 fp=0xc00051b018 sp=0xc00051afb8 pc=0x546f54
encoding/json.Marshal(0xab8be0, 0xc0006411d0, 0xf1cbf0, 0x1, 0x1, 0xc00051b0f0, 0x40cc7f)
        /usr/local/go/src/encoding/json/encode.go:161 +0x52 fp=0xc00051b090 sp=0xc00051b018 pc=0x546592
github.com/bilibili/kratos/pkg/net/http/blademaster/render.writeJSON(0xbc3120, 0xc0006aa000, 0xab8be0, 0xc0006411d0, 0x95262a, 0x415693)
        /go/pkg/mod/github.com/bilibili/kratos@v0.3.3/pkg/net/http/blademaster/render/json.go:23 +0x7b fp=0xc00051b100 sp=0xc00051b090 pc=0x951c9b
github.com/bilibili/kratos/pkg/net/http/blademaster/render.JSON.Render(...)
        /go/pkg/mod/github.com/bilibili/kratos@v0.3.3/pkg/net/http/blademaster/render/json.go:39
github.com/bilibili/kratos/pkg/net/http/blademaster/render.(*JSON).Render(0xc000641140, 0xbc3120, 0xc0006aa000, 0x0, 0xf629e0)
        <autogenerated>:1 +0xd1 fp=0xc00051b1a0 sp=0xc00051b100 pc=0x9533b1
github.com/bilibili/kratos/pkg/net/http/blademaster.(*Context).Render(0xc00032c6e0, 0xc8, 0xbbdf80, 0xc000641140)
        /go/pkg/mod/github.com/bilibili/kratos@v0.3.3/pkg/net/http/blademaster/context.go:150 +0x102 fp=0xc00051b208 sp=0xc00051b1a0 pc=0x9c1802
github.com/bilibili/kratos/pkg/net/http/blademaster.(*Context).JSON(0xc00032c6e0, 0xa4d2c0, 0xc000212580, 0x0, 0x0)
        /go/pkg/mod/github.com/bilibili/kratos@v0.3.3/pkg/net/http/blademaster/context.go:175 +0x149 fp=0xc00051b280 sp=0xc00051b208 pc=0x9c1ba9
github.com/bilibili/discovery/http.renew(0xc00032c6e0)
        /app/discovery/http/discovery.go:51 +0xd4 fp=0xc00051b2d0 sp=0xc00051b280 pc=0x9e08b4
github.com/bilibili/kratos/pkg/net/http/blademaster.(*Context).Next(0xc00032c6e0)
        /go/pkg/mod/github.com/bilibili/kratos@v0.3.3/pkg/net/http/blademaster/context.go:64 +0x3b fp=0xc00051b2f0 sp=0xc00051b2d0 pc=0x9c145b
github.com/bilibili/kratos/pkg/net/http/blademaster.Logger.func1(0xc00032c6e0)
        /go/pkg/mod/github.com/bilibili/kratos@v0.3.3/pkg/net/http/blademaster/logger.go:27 +0x127 fp=0xc00051b960 sp=0xc00051b2f0 pc=0x9cc9c7
github.com/bilibili/kratos/pkg/net/http/blademaster.HandlerFunc.ServeHTTP(0xb2b648, 0xc00032c6e0)
        /go/pkg/mod/github.com/bilibili/kratos@v0.3.3/pkg/net/http/blademaster/server.go:72 +0x30 fp=0xc00051b978 sp=0xc00051b960 pc=0x9c4ff0
github.com/bilibili/kratos/pkg/net/http/blademaster.Handler.ServeHTTP-fm(0xc00032c6e0)
        /go/pkg/mod/github.com/bilibili/kratos@v0.3.3/pkg/net/http/blademaster/server.go:64 +0x39 fp=0xc00051b998 sp=0xc00051b978 pc=0x9d12d9
github.com/bilibili/kratos/pkg/net/http/blademaster.(*Context).Next(0xc00032c6e0)
        /go/pkg/mod/github.com/bilibili/kratos@v0.3.3/pkg/net/http/blademaster/context.go:64 +0x3b fp=0xc00051b9b8 sp=0xc00051b998 pc=0x9c145b
github.com/bilibili/kratos/pkg/net/http/blademaster.Trace.func1(0xc00032c6e0)
        /go/pkg/mod/github.com/bilibili/kratos@v0.3.3/pkg/net/http/blademaster/trace.go:38 +0x610 fp=0xc00051ba68 sp=0xc00051b9b8 pc=0x9cfd70
github.com/bilibili/kratos/pkg/net/http/blademaster.HandlerFunc.ServeHTTP(0xb2b670, 0xc00032c6e0)
        /go/pkg/mod/github.com/bilibili/kratos@v0.3.3/pkg/net/http/blademaster/server.go:72 +0x30 fp=0xc00051ba80 sp=0xc00051ba68 pc=0x9c4ff0
github.com/bilibili/kratos/pkg/net/http/blademaster.Handler.ServeHTTP-fm(0xc00032c6e0)
        /go/pkg/mod/github.com/bilibili/kratos@v0.3.3/pkg/net/http/blademaster/server.go:64 +0x39 fp=0xc00051baa0 sp=0xc00051ba80 pc=0x9d12d9
github.com/bilibili/kratos/pkg/net/http/blademaster.(*Context).Next(0xc00032c6e0)
        /go/pkg/mod/github.com/bilibili/kratos@v0.3.3/pkg/net/http/blademaster/context.go:64 +0x3b fp=0xc00051bac0 sp=0xc00051baa0 pc=0x9c145b
github.com/bilibili/kratos/pkg/net/http/blademaster.Recovery.func1(0xc00032c6e0)
        /go/pkg/mod/github.com/bilibili/kratos@v0.3.3/pkg/net/http/blademaster/recovery.go:30 +0x4e fp=0xc00051baf0 sp=0xc00051bac0 pc=0x9cf18e
github.com/bilibili/kratos/pkg/net/http/blademaster.HandlerFunc.ServeHTTP(0xb2b668, 0xc00032c6e0)
        /go/pkg/mod/github.com/bilibili/kratos@v0.3.3/pkg/net/http/blademaster/server.go:72 +0x30 fp=0xc00051bb08 sp=0xc00051baf0 pc=0x9c4ff0
github.com/bilibili/kratos/pkg/net/http/blademaster.Handler.ServeHTTP-fm(0xc00032c6e0)
        /go/pkg/mod/github.com/bilibili/kratos@v0.3.3/pkg/net/http/blademaster/server.go:64 +0x39 fp=0xc00051bb28 sp=0xc00051bb08 pc=0x9d12d9
github.com/bilibili/kratos/pkg/net/http/blademaster.(*Context).Next(0xc00032c6e0)
        /go/pkg/mod/github.com/bilibili/kratos@v0.3.3/pkg/net/http/blademaster/context.go:64 +0x3b fp=0xc00051bb48 sp=0xc00051bb28 pc=0x9c145b
github.com/bilibili/kratos/pkg/net/http/blademaster.(*Engine).handleContext(0xc0001b6500, 0xc00032c6e0)
        /go/pkg/mod/github.com/bilibili/kratos@v0.3.3/pkg/net/http/blademaster/server.go:323 +0x417 fp=0xc00051bbd0 sp=0xc00051bb48 pc=0x9c6917
github.com/bilibili/kratos/pkg/net/http/blademaster.(*Engine).ServeHTTP(0xc0001b6500, 0xbc3120, 0xc0006aa000, 0xc0003be300)
        /go/pkg/mod/github.com/bilibili/kratos@v0.3.3/pkg/net/http/blademaster/server.go:494 +0xb9 fp=0xc00051bbf0 sp=0xc00051bbd0 pc=0x9c81d9
net/http.serverHandler.ServeHTTP(0xc00063e0e0, 0xbc3120, 0xc0006aa000, 0xc0003be300)
        /usr/local/go/src/net/http/server.go:2843 +0xa3 fp=0xc00051bc20 sp=0xc00051bbf0 pc=0x7b7b83
net/http.(*conn).serve(0xc0001b4500, 0xbc4ea0, 0xc000150c40)
        /usr/local/go/src/net/http/server.go:1925 +0x8ad fp=0xc00051bfc8 sp=0xc00051bc20 pc=0x7b338d
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00051bfd0 sp=0xc00051bfc8 pc=0x471521
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2969 +0x36c
...
...
...
```

**Comment by ty666** [comment]
https://github.com/bilibili/discovery/blob/87e53c31856920901b940732bf0c4e0d5713e1e7/model/instance.go#L284

定位了一下，发现这一行也应该深拷贝。
我可以提一个 pr 吗？

**Comment by ma642** [comment]
Instance.Metadata只有读，没有写，为什么panic？
